# Makefile for building main program and tests
#
# SYNOPSIS:
#
#   make [all]   - makes everything
#   make mainrun - makes the main target
#   make testrun - makes the test units target
#   make clean   - removes all files generated by make
#
# Workflow directories
MAIN_CATALOG = main
TEST_CATALOG = unittest

# Set Google Test's
GTEST_DIR = $(TEST_CATALOG)
CPPFLAGS = -isystem $(GTEST_DIR)/include
GTEST_LIB = -lgtest -lpthread
GTEST_LDFLAGS = -L$(GTEST_DIR)/lib

# C compiler
CC = gcc
CCFLAGS = -std=c99
CCLDFLAG = -lm

# C++ compiler
CXX = g++
CXXFLAGS = -g -Wall -Wextra -pthread -std=c++11

# Main program
TARGET = mainrun
TARGETSRC = $(wildcard $(MAIN_CATALOG)/*.c)
TARGETOBJ = $(patsubst $(MAIN_CATALOG)/%.c,$(MAIN_CATALOG)/%.o,$(TARGETSRC))

# Unit tests
TESTRUN = testrun
TESTSRC = $(wildcard $(TEST_CATALOG)/*.cpp)
TESTOBJ = $(filter-out $(MAIN_CATALOG)/main.o, $(TARGETOBJ)) \
	$(patsubst $(TEST_CATALOG)/%.cpp,$(TEST_CATALOG)/%.o,$(TESTSRC))

# For unit tests
TESTFLAGS = -I$(MAIN_CATALOG) -Wall

.PHONY: $(TARGET) $(TESTRUN) all clean

all : $(TARGET) $(TESTRUN)

$(MAIN_CATALOG)/%.o : $(MAIN_CATALOG)/%.c
	$(CC) $(CCFLAGS) -c $< -o $@

$(TARGET) : $(TARGETOBJ)
	$(CC) $^ -o $@ $(CCLDFLAG)
	
$(TEST_CATALOG)/%.o : $(TEST_CATALOG)/%.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(TESTFLAGS) -c $< -o $@

$(TESTRUN) : $(TESTOBJ)
	$(CXX) $(GTEST_LDFLAGS) $^ -o $@ $(GTEST_LIB)

clean :
	-rm -f $(MAIN_CATALOG)/*.o $(TARGET)
	-rm -f $(TEST_CATALOG)/*.o $(TESTRUN)

